steps:
  # 构建Docker镜像
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/stock-selector', '.']
    
  # 推送镜像到容器注册表  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/stock-selector']
    
  # 部署到Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', 'stock-selector',
           '--image', 'gcr.io/$PROJECT_ID/stock-selector',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--allow-un